### ISSUE TITLE
Please document how to use with the new csproj

### ISSUE THREAD

**Issue by oliverjanik** [nil4/dotnet-transform-xdt#12]

**Comment by nil4** [comment]
@oliverjanik The readme file in this repository includes a [section about using this tool with csproj tooling](https://github.com/nil4/dotnet-transform-xdt#-how-to-use-with-msbuildcsproj-tooling).

There is also a separate repository with samples you can explore, or clone and run: https://github.com/nil4/xdt-samples

I'll close the issue for now, as documentation is already available. Please feel free to reopen if you find something missing or unclear.
