### ISSUE TITLE
Nice but

### ISSUE THREAD

**Issue by olivier-voutat** [nil4/dotnet-transform-xdt#18]
I suggest creating an installer (with framework 462 for an exe) instead of a nuget package.

Two reasons:
1) Install once, and allow all applications to use it is easier
2) if the application is aspnet core with framework, it is not compatible

**Comment by nil4** [comment]
Thank you for your feedback, @olivier-voutat; that's an interesting suggestion. 

It looks like it will soon be possible to install tools like `dotnet-transform-xdt` globally, and call them as if they were executables (details [here](http://www.natemcmaster.com/blog/2018/02/02/dotnet-global-tool/) and [here](https://dasmulli.blog/2018/01/23/exploring-global-net-core-tools/)). I think this would cover your first use case without giving up on cross-platform advantages. As the global tool support is still being actively developed, I plan to evaluate it in more depth once it stabilizes (likely after .NET Core 2.1 is released).

The current `dotnet-transform-xdt` tool works fine in an ASP.NET Core application targeting the full .NET framework. You can test this by cloning the [samples repository](https://github.com/nil4/xdt-samples) and changing e.g. the [`WebServerSettingsSample.csproj`](https://github.com/nil4/xdt-samples/blob/master/WebServerSettingsSample/WebServerSettingsSample.csproj) file from:

```xml
<TargetFramework>netcoreapp2.0</TargetFramework>
```
to 
```xml
<TargetFramework>net462</TargetFramework>
```
Run `dotnet restore`, then `dotnet publish -c Release`, and the tool will be invoked to transform `Web.config`. I hope this helps.

**Comment by olivier-voutat** [comment]
It is what I did. And I put the exe in my C:\Program Files\dotnet folder (in the TFS agents servers too). So no need to have it in all the projects.

**Comment by nil4** [comment]
Glad to hear that you found a workaround. 

I will close this issue and open one to track making `dotnet-transform-xdt` available as a global tool.

**Comment by nil4** [comment]
@olivier-voutat a preview version of the .NET CLI global tool is now available; [details here](https://github.com/nil4/dotnet-transform-xdt/issues/19#issuecomment-394091960).

A standalone executable for .NET 4.6.1 or later is also produced on every AppVeyor build: https://ci.appveyor.com/project/nil4/dotnet-transform-xdt/build/artifacts
