### ISSUE TITLE
Update doc: dotnet new -t web is not working any more

### ISSUE THREAD

**Issue by karelkral** [nil4/dotnet-transform-xdt#30]
Hello, there is outdated instruction in section "Project-level dotnet-transform-xdt tool"  `run dotnet new -t web`. 

Command line switch -t in not working any more, is replaced by  `run dotnet new web`
https://stackoverflow.com/a/42807347/245460

Also noted that `run dotnet new web` does not create `web.config` any more, so you should add web.config to project manually.

**Comment by nil4** [comment]
You're right, this part of the readme file was probably written in (or soon after) the project.json days. 

Thank you for your PR, @karelkral!
