### ISSUE TITLE
transform-xdt hangs intermittently

### ISSUE THREAD

**Issue by enginaar** [nil4/dotnet-transform-xdt#39]
Hi,

I'm using Microsoft.DotNet.Xdt.Tools version 2.0.0 .Net Core 2.0 and added the following command to run after publish but it hangs intermittently.

`dotnet transform-xdt -x web.config -t web.$(ConfigurationName).config -o $(PublishDir)web.config`

I test the command as below when I encounter publish is hanging and it hangs the same way.

`dotnet transform-xdt -x web.config -t web.Staging.config -o web.test.config`

I wasn't able to see it returning an error message to help investigating the issue further, don't know if the tool stores logs either. Problem disappears as it appeared after a period of time that I'm not sure if it's a fixed amount.

Can I prevent the hangs or find out the reason?

**Comment by nil4** [comment]
Try adding `--verbose` (or `-v`) to the command line, i.e.:

```
dotnet transform-xdt --verbose -x web.config -t web.$(ConfigurationName).config -o $(PublishDir)web.config
```

This will print a detailed log of operations performed, with each line of the output prefixed by `[XDT]` or `[dotnet-xdt]`, which should hopefully point out what the issue might be.

**Comment by nil4** [comment]
@enginaar I will close this issue as I haven't heard back in a while. If the issue persists, please include a detailed log with the XDT transform output, or ideally, a small, isolated project that reproduces the problem, and I will reopen.
