### ISSUE TITLE
Option --quiet and -q are not recognized

### ISSUE THREAD

**Issue by Vermis0** [nil4/dotnet-transform-xdt#46]
v2.2.0

According to the help there is a quiet option that will only print error messages. However, it is not recognized as an option.

Options:
  --help|-h|-?     Print usage information
  --quiet|-q       Print only error messages
  --verbose|-v     Print verbose messages while transforming

>dotnet-xdt.exe --source "source.config" --transform "transform.config" --output "output.config" --quiet
[dotnet-xdt] Invalid argument: '--quiet'

>dotnet-xdt.exe -s source.config -t transform.config -o output.config -q
[dotnet-xdt] Invalid argument: '-q'

**Comment by nil4** [comment]
Nice find, thank you for opening this issue @Vermis0.

The `quiet` option was removed in c2bcb667, but the help text was not updated accordingly; fixed now with #47.
